### ISSUE TITLE
Support for nomad packs

### ISSUE THREAD

**Issue by devantler** [jonasvinther/nomad-gitops-operator#3]
Hey, this tool is awesome! 🤩

Do you have any plans to support nomad packs as an alternative to nomad jobs? 👀

**Comment by jonasvinther** [comment]
That is actually an excellent question. I have been thinking about how to include Nomad pack in this. Nomad pack has a `render` command that will render your template into a nomad job file. So you could utilize Nomad Pack by having some automation that will render your Nomad pack template and commit it into your gitops repo and then Nomoporator will pick it up. That way you always know exactly what is deployed to your nomad cluster. That way you also have a much cleaner cut between what is defined in your gitops repo and how it got there. Does that make sense? And what do you think about that approach :)

**Comment by devantler** [comment]
Interesting! I will try to see if i can make it work. I was not aware of the `render` method and utilizing it as suggested seems like a good way to bridge the gap to support gitops.

But as I like to keep my nomad environment (variables, volumes) separate to my nomad packs to avoid leaking values to variables, I will have to find a good way to do the automation such that:

- input variables to nomad pack render can be obtained from a separate private repository
- the render method can render jobs to a different repository than where the nomad packs reside.
- the workflow is triggered automatically when a nomad pack is updated.

I am not sure how well GitHub Actions can interact with other repositories than the one they reside in, but if that is possible, maybe I can do it with a custom GitHub Action :-)
